### ISSUE TITLE
Error in 2 players elo rating calculation

### ISSUE THREAD

**Issue by Scalpweb** [radoneman/elo-rating-multiplayer#1]
https://github.com/radoneman/elo-rating-multiplayer/blob/3b78e9bd1d98908cb948064d97b7e95e29e1fef2/src/com/elo/EloRating.java#L118

Should be 0 instead of 0.5, I guess.

**Comment by radoneman** [comment]
You're right, it should be 0. Thanks for finding this!

**Comment by jmart1** [comment]
Was this fixed?

**Comment by radoneman** [comment]
Yes, please see the source code.
